"""initial schema

Revision ID: ac09a5636744
Revises:
Create Date: 2026-05-03 03:39:18.747403+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac09a5636744'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'annual', 'irregular', name='dataset_frequency', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_slug'), 'datasets', ['slug'], unique=True)
    op.create_table('dataset_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_fields_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_fields')),
    sa.UniqueConstraint('dataset_id', 'field_name', name=op.f('uq_dataset_fields_dataset_id'))
    )
    op.create_index(op.f('ix_dataset_fields_dataset_id'), 'dataset_fields', ['dataset_id'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('source_uuid', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('link_text', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_source_files_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_files'))
    )
    op.create_index(op.f('ix_source_files_dataset_id'), 'source_files', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_source_files_source_uuid'), 'source_files', ['source_uuid'], unique=True)
    op.create_table('data_exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('currency_name', sa.String(length=64), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('unit_multiplier', sa.Integer(), nullable=False),
    sa.Column('rate_per_unit', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], name=op.f('fk_data_exchange_rates_source_file_id_source_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_exchange_rates')),
    sa.UniqueConstraint('snapshot_date', 'currency_code', name='uq_data_exchange_rates_snapshot_date_currency_code')
    )
    op.create_index(op.f('ix_data_exchange_rates_currency_code'), 'data_exchange_rates', ['currency_code'], unique=False)
    op.create_index(op.f('ix_data_exchange_rates_snapshot_date'), 'data_exchange_rates', ['snapshot_date'], unique=False)
    op.create_index('ix_data_exchange_rates_snapshot_date_currency_code', 'data_exchange_rates', ['snapshot_date', 'currency_code'], unique=False)
    op.create_index(op.f('ix_data_exchange_rates_source_file_id'), 'data_exchange_rates', ['source_file_id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='ingestion_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_added', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_ingestion_logs_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], name=op.f('fk_ingestion_logs_source_file_id_source_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_logs'))
    )
    op.create_index(op.f('ix_ingestion_logs_dataset_id'), 'ingestion_logs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_source_file_id'), 'ingestion_logs', ['source_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_logs_source_file_id'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_dataset_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_data_exchange_rates_source_file_id'), table_name='data_exchange_rates')
    op.drop_index('ix_data_exchange_rates_snapshot_date_currency_code', table_name='data_exchange_rates')
    op.drop_index(op.f('ix_data_exchange_rates_snapshot_date'), table_name='data_exchange_rates')
    op.drop_index(op.f('ix_data_exchange_rates_currency_code'), table_name='data_exchange_rates')
    op.drop_table('data_exchange_rates')
    op.drop_index(op.f('ix_source_files_source_uuid'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_dataset_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_dataset_fields_dataset_id'), table_name='dataset_fields')
    op.drop_table('dataset_fields')
    op.drop_index(op.f('ix_datasets_slug'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
